### ISSUE TITLE
TODO List 

### ISSUE THREAD

**Issue by Morozov-5F** [Morozov-5F/stm32-zigbee-sniffer#1]
- [x] LCD Display initialization via I2C
- [x] Radio module setup via SPI 
- [x] Radio module channel switch by button press
- [x] Actual air sniffing
